<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.seal</groupId>
    <artifactId>SEAL</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>SEAL</name>
    <description>Secured Examination Access and Lockdown</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Compile as Java 21 -->
        <maven.compiler.release>21</maven.compiler.release>

        <javafx.version>21.0.6</javafx.version>
    </properties>


    <dependencies>

        <!-- JavaFX Controls: Button, Label, TextField, layouts, etc. -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>


        <!-- Allows us to use FXML -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>

    </dependencies>


    <build>

        <plugins>

            <!-- Java compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>

                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>


            <!-- Lets us run JavaFX using: ./mvnw javafx:run -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>

                <configuration>
                    <mainClass>com.example.seal/com.example.seal.Main</mainClass>
                </configuration>
            </plugin>

        </plugins>

    </build>

</project>